before_script:
- export ANDROID_HOME= "Users/truongquockhanh/Library/Android/sdk"
- bundle install
stages :
- build
- test
- quality_assurance
- deploy

build_job :
  stage : build
  script :
  - ./gradlew assembleDebug
  artifacts :
    paths:
    - app/build/outputs/

unit_test:
  stage : test
  script :
  - ./gradlew test
  artifacts :
    name : "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when : on_failure
    expire_in : 4 days
    paths :
    - app/build/reports/tests/

static_analytic:
  stage : quality_assurance
  script :
  - ./gradlew pmd
  - ./gradlew checkstyle
  - ./gradlew findbugs
  - ./gradlew lint
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    when: on_failure
    expire_in: 4 days
    paths:
      - app/build/reports/

